using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Projectile : MonoBehaviour
{

    private Rigidbody rb;       // 내부에서 사용 할 rb;

    public float moveSpeed;         // 이동 속도
    public float damagedAmount;     // 데미지 량
    private bool hasDamaged;        // flag 선언




    void Start()
    {
        rb = GetComponent<Rigidbody>();
        rb.velocity = transform.forward * moveSpeed ;    // rb의 앞쪽 방향으로 총알 이동 속도를 입력
    }

    private void OnTriggerEnter( Collider col )
    {
        if ( col.tag == "Enemy" && !hasDamaged )
        {
            hasDamaged = true ;
        }

        Destroy ( gameObject ) ;        // Trigger 충돌이 일어나면 파괴
    }

}
